# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75cd5fcf17890712eaf5b08f82a4ea90dba2e2527e84c6c119ae63d546f3bcc3c69f7f0daacc427bada2139117196235d504ea2ff6d149016d8c58d518d09233

test:
  secret_key_base: b8a67aa1c7584975a409eff696c39faec0b1afac2642ab3228a6af06eeb62d954beadadba2823cff528c60626fb5e9f087a178c0deb6d8ddaf5d249379c82224

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: b8a67aa1c7584975a409eff696c39faec0b1afac2642ab3228a6af06eeb62d954beadadba2823cff528c60626fb5e9f087a178c0deb6d8ddaf5d249379c82224
